"""SQLAlchemy ORM models for the Risk Prediction Engine.

Provides persistent storage for risk scores, alerts, and trend data
with proper indexing for common query patterns following the
existing audit infrastructure conventions.
"""

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import JSON as SA_JSON
from sqlalchemy import DateTime, Float, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from regulaforge.infrastructure.persistence.database import Base
from regulaforge.infrastructure.persistence.models.base import GUID, TimestampMixin, VersionMixin


class RiskScoreModel(TimestampMixin, VersionMixin, Base):
    """ORM model for the risk_scores table.

    Stores computed risk scores for entities and assessments
    with category breakdowns and model metadata.
    """

    __tablename__ = "risk_scores"

    id: Mapped[GUID] = mapped_column(
        GUID,
        primary_key=True,
        default=uuid4,
        comment="Unique risk score identifier",
    )
    entity_id: Mapped[GUID] = mapped_column(
        GUID,
        nullable=False,
        index=True,
        comment="Entity UUID this score belongs to",
    )
    assessment_id: Mapped[GUID] = mapped_column(
        GUID,
        nullable=True,
        index=True,
        comment="Optional assessment UUID that generated this score",
    )
    overall_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Aggregated risk score (0-100)",
    )
    category_scores: Mapped[dict] = mapped_column(
        SA_JSON,
        nullable=True,
        default=dict,
        comment="Per-category risk score breakdown",
    )
    risk_level: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="Risk level classification",
    )
    confidence_lower: Mapped[float] = mapped_column(
        Float,
        nullable=True,
        comment="Lower bound of confidence interval",
    )
    confidence_upper: Mapped[float] = mapped_column(
        Float,
        nullable=True,
        comment="Upper bound of confidence interval",
    )
    prediction_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        comment="Date the score was computed or predicted",
    )
    model_version: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="rule_based_v1",
        comment="Model version used for prediction",
    )
    features_used: Mapped[dict] = mapped_column(
        SA_JSON,
        nullable=True,
        default=list,
        comment="List of features used in calculation",
    )

    __table_args__ = (
        Index("ix_risk_scores_entity_id_prediction_date", "entity_id", "prediction_date"),
        Index("ix_risk_scores_entity_id_risk_level", "entity_id", "risk_level"),
        Index("ix_risk_scores_assessment_id", "assessment_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<RiskScoreModel id={self.id} entity={self.entity_id} "
            f"score={self.overall_score} level={self.risk_level}>"
        )


class RiskAlertModel(TimestampMixin, VersionMixin, Base):
    """ORM model for the risk_alerts table.

    Stores risk alerts generated by threshold breaches and
    emerging risk detection with full lifecycle tracking.
    """

    __tablename__ = "risk_alerts"

    id: Mapped[GUID] = mapped_column(
        GUID,
        primary_key=True,
        default=uuid4,
        comment="Unique alert identifier",
    )
    entity_id: Mapped[GUID] = mapped_column(
        GUID,
        nullable=False,
        index=True,
        comment="Entity UUID this alert pertains to",
    )
    alert_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="Type of alert (e.g. threshold_breach, emerging_risk)",
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="Alert severity level",
    )
    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Human-readable alert message",
    )
    details: Mapped[dict] = mapped_column(
        SA_JSON,
        nullable=True,
        default=dict,
        comment="Additional alert details and metadata",
    )
    triggered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
        comment="When the alert was triggered (UTC)",
    )
    acknowledged_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the alert was acknowledged (UTC)",
    )
    acknowledged_by: Mapped[GUID] = mapped_column(
        GUID,
        nullable=True,
        comment="UUID of the user who acknowledged",
    )
    resolved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the alert was resolved (UTC)",
    )

    __table_args__ = (
        Index("ix_risk_alerts_entity_id_triggered_at", "entity_id", "triggered_at"),
        Index("ix_risk_alerts_entity_id_severity", "entity_id", "severity"),
        Index("ix_risk_alerts_active", "entity_id", "resolved_at"),
        Index("ix_risk_alerts_alert_type_triggered_at", "alert_type", "triggered_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<RiskAlertModel id={self.id} entity={self.entity_id} "
            f"type={self.alert_type} severity={self.severity}>"
        )


class RiskTrendModel(TimestampMixin, VersionMixin, Base):
    """ORM model for the risk_trends table.

    Stores materialized historical risk score snapshots for
    efficient trend analysis and forecasting queries.
    """

    __tablename__ = "risk_trends"

    id: Mapped[GUID] = mapped_column(
        GUID,
        primary_key=True,
        default=uuid4,
        comment="Unique trend entry identifier",
    )
    entity_id: Mapped[GUID] = mapped_column(
        GUID,
        nullable=False,
        index=True,
        comment="Entity UUID",
    )
    snapshot_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Date of the risk snapshot",
    )
    overall_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Risk score at snapshot date",
    )
    risk_level: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Risk level at snapshot date",
    )
    category_scores: Mapped[dict] = mapped_column(
        SA_JSON,
        nullable=True,
        default=dict,
        comment="Category scores at snapshot date",
    )
    score_change: Mapped[float] = mapped_column(
        Float,
        nullable=True,
        default=0.0,
        comment="Change from previous snapshot",
    )
    snapshot_metadata: Mapped[dict] = mapped_column(
        SA_JSON,
        nullable=True,
        default=dict,
        comment="Additional snapshot metadata",
    )

    __table_args__ = (
        Index(
            "ix_risk_trends_entity_id_snapshot_date",
            "entity_id",
            "snapshot_date",
        ),
        Index(
            "ix_risk_trends_entity_id_score_change",
            "entity_id",
            "score_change",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<RiskTrendModel id={self.id} entity={self.entity_id} "
            f"date={self.snapshot_date} score={self.overall_score}>"
        )
