"""Modular dependency injection providers.

Split from the monolithic dependencies.py to improve
maintainability and follow the Single Responsibility Principle.
"""

from regulaforge.interfaces.api.dependencies.auth import get_current_user_id
from regulaforge.interfaces.api.dependencies.database import get_db_session
from regulaforge.interfaces.api.dependencies.infrastructure import (
    get_event_publisher,
    get_jwt_service,
    get_llm_provider,
    get_password_service,
)
from regulaforge.interfaces.api.dependencies.repositories import (
    get_assessment_repo,
    get_document_repo,
    get_entity_repo,
    get_regulation_repo,
    get_role_repo,
    get_user_repo,
)
from regulaforge.interfaces.api.dependencies.use_cases import (
    get_add_finding_uc,
    get_add_requirement_uc,
    get_approve_assessment_uc,
    get_change_password_uc,
    get_complete_assessment_uc,
    get_create_assessment_uc,
    get_create_entity_uc,
    get_create_regulation_uc,
    get_deactivate_entity_uc,
    get_delete_document_uc,
    get_entity_children_uc,
    get_entity_hierarchy_uc,
    get_get_assessment_uc,
    get_get_document_uc,
    get_get_entity_uc,
    get_get_regulation_uc,
    get_list_assessments_uc,
    get_login_uc,
    get_publish_regulation_uc,
    get_refresh_uc,
    get_register_uc,
    get_search_documents_uc,
    get_search_entities_uc,
    get_search_regulations_uc,
    get_start_assessment_uc,
    get_update_entity_uc,
    get_update_regulation_uc,
    get_upload_document_uc,
    get_verify_document_uc,
)

__all__ = [
    "get_add_finding_uc",
    "get_add_requirement_uc",
    "get_approve_assessment_uc",
    "get_assessment_repo",
    "get_change_password_uc",
    "get_complete_assessment_uc",
    "get_create_assessment_uc",
    "get_create_entity_uc",
    "get_create_regulation_uc",
    "get_current_user_id",
    "get_db_session",
    "get_deactivate_entity_uc",
    "get_delete_document_uc",
    "get_document_repo",
    "get_entity_children_uc",
    "get_entity_hierarchy_uc",
    "get_entity_repo",
    "get_event_publisher",
    "get_get_assessment_uc",
    "get_get_document_uc",
    "get_get_entity_uc",
    "get_get_regulation_uc",
    "get_jwt_service",
    "get_list_assessments_uc",
    "get_llm_provider",
    "get_login_uc",
    "get_password_service",
    "get_publish_regulation_uc",
    "get_refresh_uc",
    "get_register_uc",
    "get_regulation_repo",
    "get_role_repo",
    "get_search_documents_uc",
    "get_search_entities_uc",
    "get_search_regulations_uc",
    "get_start_assessment_uc",
    "get_update_entity_uc",
    "get_update_regulation_uc",
    "get_upload_document_uc",
    "get_user_repo",
    "get_verify_document_uc",
]
