apiVersion: v1
kind: Namespace
metadata:
  name: regulaforge
  labels:
    app.kubernetes.io/name: regulaforge
    app.kubernetes.io/part-of: regulaforge
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
